ALTER TYPE "FeedbackType" ADD VALUE IF NOT EXISTS 'ENCOURAGEMENT';
ALTER TYPE "FeedbackType" ADD VALUE IF NOT EXISTS 'COMMUNITY_SERVICE';
ALTER TYPE "FeedbackType" ADD VALUE IF NOT EXISTS 'ENVIRONMENTAL_ACT';
