CREATE TYPE "FeedbackStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

ALTER TYPE "NotificationType" ADD VALUE 'FEEDBACK_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'FEEDBACK_REJECTED';

ALTER TABLE "Feedback"
ADD COLUMN "status" "FeedbackStatus" NOT NULL DEFAULT 'APPROVED',
ADD COLUMN "reviewedAt" TIMESTAMP(3);
